backend:
  name: github
  repo: TownCloud/village-of-dundee
  squash_merges: true
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'
publish_mode: editorial_workflow
media_folder: static/uploads
public_folder: /uploads
collections:
  - label: 'Post'
    name: 'post'
    folder: 'data/news'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'date' }
      - {
          label: 'Teaser',
          name: 'teaser',
          widget: 'string',
          hint: 'One sentence summary of the news.',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Document'
    name: 'document'
    folder: 'data/docs'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'date' }
      - label: 'Document'
        name: 'documentURL'
        widget: 'file'
        media_library:
          config:
            multiple: false
      - { label: 'Category', name: 'category', widget: 'string' }
      - {
          label: 'Description',
          name: 'description',
          widget: 'string',
          required: false,
          hint: 'A brief description of the attached document',
        }
  - label: 'Directory'
    name: 'directory'
    files:
      - label: 'Directory'
        name: 'directory'
        file: 'data/directory/directory.md'
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - { label: 'Date', name: 'date', widget: 'date' }
          - label: 'Directory Content'
            name: 'body'
            widget: 'markdown'

  - label: 'Content'
    name: 'content'
    files:
      - label: 'Site Configuration'
        name: 'config'
        file: 'data/setup/setup.md'
        fields:
          - label: 'Municipality'
            name: 'municipality'
            widget: 'string'
            hint: 'What is the name of your Municipality?'
          - label: 'Home Page'
            name: 'homeGroup'
            widget: 'object'
            fields:
              - label: 'Hero Image'
                name: 'heroGroup'
                widget: 'object'
                fields:
                  - label: 'Hero Image'
                    name: 'hero'
                    widget: 'image'
                    media_library:
                      config:
                        multiple: false
                  - label: 'Hero image alt text'
                    name: 'heroAltText'
                    widget: 'string'
                    hint: 'Description of the image'
              - label: 'Address'
                name: 'addressGroup'
                widget: 'object'
                fields:
                  - { label: Address, name: address, widget: string }
                  - { label: City, name: city, widget: string }
                  - { label: State, name: state, widget: string }
                  - { label: Zip Code, name: zipcode, widget: string }
              - label: 'Contact'
                name: 'contactGroup'
                widget: 'object'
                fields:
                  - {
                      label: Email,
                      name: email,
                      widget: string,
                      required: false,
                    }
                  - {
                      label: Phone,
                      name: phone,
                      widget: string,
                      required: false,
                    }
                  - { label: Fax, name: fax, widget: string, required: false }
                  - {
                      label: Facebook,
                      name: facebook,
                      widget: string,
                      required: false,
                    }
                  - {
                      label: Twitter,
                      name: twitter,
                      widget: string,
                      required: false,
                    }
                  - label: Instagram
                    name: instagram
                    widget: string
                    required: false
                  - {
                      label: Youtube,
                      name: youtube,
                      widget: string,
                      required: false,
                    }
